#!/usr/bin/env ruby
# frozen_string_literal: true

require "date"
require "digest"
require "fileutils"
require "json"
require "pathname"
require "set"
require "yaml"

ROOT = Pathname.new(__dir__).parent.expand_path
WIKI = ROOT.join("library/knowledge-base/wiki")
CONTENT_DIRS = %w[entities concepts comparisons decisions questions meta].freeze
GLOBAL_FILES = %w[index.md log.md hot.md].freeze
ALLOWED_TYPES = %w[entity concept comparison decision question meta].freeze
ALLOWED_STATUSES = %w[seed developing mature evergreen stub proposed accepted rejected deprecated superseded open resolved].freeze
ALLOWED_ENTITY_TYPES = %w[function class module service endpoint env-var config-key data-model react-component sql-table queue cron-job feature-flag].freeze
ALLOWED_CALLOUTS = %w[contradiction stale gap key-insight].freeze
SOURCE_EXTENSIONS = %w[.py .ts .tsx .js .jsx .json .toml .yaml .yml .sql .css .md .html].freeze
TODAY = Date.today.iso8601

Finding = Struct.new(:category, :path, :message, keyword_init: true)

def wiki_pages
  CONTENT_DIRS.flat_map { |dir| Dir[WIKI.join(dir, "*.md").to_s] }
    .map { |path| Pathname.new(path) }
    .reject { |path| path.basename.to_s == "_index.md" }
    .sort
end

def parse_page(path)
  text = File.read(path, encoding: "UTF-8")
  match = text.match(/\A---\s*\n(.*?)\n---\s*\n/m)
  raise "missing YAML frontmatter" unless match

  data = YAML.safe_load(match[1], permitted_classes: [], permitted_symbols: [], aliases: false) || {}
  [data, text, match.end(0)]
rescue Psych::Exception => e
  raise "invalid YAML frontmatter: #{e.message}"
end

def rel(path)
  path.relative_path_from(ROOT).to_s
end

def wiki_key(path)
  path.relative_path_from(WIKI).sub_ext("").to_s
end

def title_for(data, path)
  data["title"].to_s.empty? ? path.basename(".md").to_s : data["title"].to_s
end

def resolve_wikilink(raw, page_by_key, page_by_basename)
  target = raw.split("|", 2).first.split("#", 2).first.sub(/\.md\z/, "").sub(%r{\A/+}, "")
  return true if target.empty?
  return true if page_by_key.key?(target)

  matches = page_by_basename[File.basename(target)]
  matches&.length == 1
end

def markdown_links(text)
  text.scan(/(?<!!)\[[^\]]+\]\(([^)]+)\)/).flatten
end

def source_files
  %w[backend frontend].flat_map do |base|
    Dir[ROOT.join(base, "**/*").to_s].select do |path|
      File.file?(path) && SOURCE_EXTENSIONS.include?(File.extname(path)) &&
        !path.include?("/node_modules/") && !path.include?("/.next/") &&
        !path.include?("/__pycache__/") && !path.include?("/.venv/")
    end
  end.map { |p| Pathname.new(p) }.sort
end

def tracked_source_files
  output = IO.popen(["git", "-C", ROOT.to_s, "ls-files", "backend", "frontend"], &:read)
  output.lines.map(&:strip).reject(&:empty?).select do |path|
    SOURCE_EXTENSIONS.include?(File.extname(path))
  end.sort
end

def render_index(title, pages)
  grouped = pages.group_by { |page| parse_page(page).first["type"] || page.dirname.basename.to_s.sub(/s\z/, "") }
  body = ["# #{title}", "", "Generated by `scripts/reconcile_wiki.rb` on #{TODAY}. Do not edit manually.", ""]
  grouped.sort.each do |type, paths|
    body << "## #{type.to_s.split("-").map(&:capitalize).join(" ")}"
    body << ""
    paths.sort_by { |path| title_for(parse_page(path).first, path).downcase }.each do |path|
      data = parse_page(path).first
      body << "- [[#{wiki_key(path)}|#{title_for(data, path)}]] — `#{data["status"]}`"
    end
    body << ""
  end
  body.join("\n") + "\n"
end

def write_global_state(pages)
  WIKI.join("index.md").write(render_index("Ring Rookie Code Wiki", pages))

  CONTENT_DIRS.each do |dir|
    paths = pages.select { |path| path.dirname.basename.to_s == dir }
    next if paths.empty?

    WIKI.join(dir, "_index.md").write(render_index("#{dir.capitalize} Index", paths))
  end

  entries = pages.map { |path| [path, parse_page(path).first] }
  recent = entries.sort_by { |path, data| [data["updated"].to_s, path.to_s] }.reverse.first(50)
  hot = ["# Hot Wiki Pages", "", "The 50 most recently updated atomic pages. Generated on #{TODAY}.", ""]
  recent.each { |path, data| hot << "- `#{data["updated"]}` [[#{wiki_key(path)}|#{title_for(data, path)}]]" }
  WIKI.join("hot.md").write(hot.join("\n") + "\n")

  counts = entries.group_by { |_path, data| data["type"] }.transform_values(&:length)
  log = ["# Wiki Reconciliation Log", "", "## #{TODAY}", "", "- Atomic pages: #{pages.length}"]
  counts.sort.each { |type, count| log << "- #{type}: #{count}" }
  log.concat(["- Source files covered: #{tracked_source_files.length}", "- Generator: `scripts/reconcile_wiki.rb`", ""])
  WIKI.join("log.md").write(log.join("\n") + "\n")

  hashes = {}
  source_files.each { |path| hashes[rel(path)] = Digest::SHA256.file(path).hexdigest }
  pages.each { |path| hashes[rel(path)] = Digest::SHA256.file(path).hexdigest }
  FileUtils.mkdir_p(WIKI.join(".legion"))
  WIKI.join(".legion/file-hashes.json").write(JSON.pretty_generate({ "generated_at" => TODAY, "algorithm" => "sha256", "files" => hashes.sort.to_h }) + "\n")
  format_targets = [
    WIKI.join("index.md"), WIKI.join("log.md"), WIKI.join("hot.md"),
    WIKI.join(".legion/file-hashes.json"),
    *CONTENT_DIRS.map { |dir| WIKI.join(dir, "_index.md") }.select(&:file?)
  ]
  prettier = ROOT.join("frontend/node_modules/.bin/prettier")
  system(prettier.to_s, "--write", *format_targets.map(&:to_s), out: File::NULL) if prettier.executable?
end

def lint(pages)
  findings = []
  parsed = {}
  pages.each do |path|
    begin
      parsed[path] = parse_page(path)
    rescue StandardError => e
      findings << Finding.new(category: "metadata", path: rel(path), message: e.message)
    end
  end

  page_by_key = pages.to_h { |path| [wiki_key(path), path] }
  page_by_basename = pages.group_by { |path| path.basename(".md").to_s }
  incoming = Hash.new(0)
  required = %w[type title created updated tags status]

  parsed.each do |path, (data, text, _body_start)|
    required.each do |field|
      findings << Finding.new(category: "metadata", path: rel(path), message: "missing #{field}") unless data.key?(field)
    end
    findings << Finding.new(category: "metadata", path: rel(path), message: "invalid type #{data["type"].inspect}") unless ALLOWED_TYPES.include?(data["type"])
    findings << Finding.new(category: "metadata", path: rel(path), message: "invalid status #{data["status"].inspect}") unless ALLOWED_STATUSES.include?(data["status"])
    %w[created updated].each do |field|
      findings << Finding.new(category: "metadata", path: rel(path), message: "#{field} must be a quoted string") unless data[field].is_a?(String)
    end
    if data["type"] == "entity"
      %w[entity_type path language last_commit_hash].each do |field|
        findings << Finding.new(category: "metadata", path: rel(path), message: "missing entity field #{field}") if data[field].to_s.empty?
      end
      unless ALLOWED_ENTITY_TYPES.include?(data["entity_type"])
        findings << Finding.new(category: "metadata", path: rel(path), message: "invalid entity_type #{data["entity_type"].inspect}")
      end
      source = ROOT.join(data["path"].to_s)
      findings << Finding.new(category: "coverage", path: rel(path), message: "source path does not exist: #{data["path"]}") unless source.file?
    end
    findings << Finding.new(category: "atomicity", path: rel(path), message: "#{text.lines.length} lines exceeds 300") if text.lines.length > 300

    text.scan(/\[\[([^\]]+)\]\]/).flatten.each do |target|
      clean = target.split("|", 2).first.split("#", 2).first.sub(/\.md\z/, "").sub(%r{\A/+}, "")
      if resolve_wikilink(target, page_by_key, page_by_basename)
        resolved = page_by_key[clean] || (page_by_basename[File.basename(clean)]&.first)
        incoming[resolved] += 1 if resolved
      else
        findings << Finding.new(category: "dead-link", path: rel(path), message: "unresolved wikilink [[#{target}]]")
      end
    end

    text.scan(/^> \[!([^\]]+)\]/).flatten.each do |callout|
      findings << Finding.new(category: "callout", path: rel(path), message: "unsupported callout #{callout}") unless ALLOWED_CALLOUTS.include?(callout)
    end

    markdown_links(text).each do |target|
      next if target.match?(%r{\A(?:https?://|mailto:|#)})
      clean = target.split("#", 2).first
      next if clean.empty?
      destination = path.dirname.join(clean).cleanpath
      findings << Finding.new(category: "docs-link", path: rel(path), message: "missing relative link target #{target}") unless destination.exist?
    end
  end

  indexed_targets = Set.new(pages)
  pages.each do |path|
    findings << Finding.new(category: "orphan", path: rel(path), message: "page absent from generated indexes") unless indexed_targets.include?(path)
  end

  decisions = parsed.select { |_path, (data, _text, _offset)| data["type"] == "decision" }
  decisions.each do |path, (data, _text, _offset)|
    %w[supersedes superseded_by].each do |field|
      Array(data[field]).compact.reject(&:empty?).each do |target|
        findings << Finding.new(category: "adr-chain", path: rel(path), message: "#{field} target missing: #{target}") unless resolve_wikilink(target.to_s, page_by_key, page_by_basename)
      end
    end
  end

  covered = parsed.values.map { |data, _text, _offset| data["path"] if data["type"] == "entity" }.compact.to_set
  tracked_source_files.each do |source|
    findings << Finding.new(category: "coverage", path: source, message: "tracked source lacks an entity/module page") unless covered.include?(source)
  end

  findings
end

abort "wiki directory not found: #{WIKI}" unless WIKI.directory?
pages = wiki_pages
abort "no atomic wiki pages found" if pages.empty?
write_global_state(pages)
findings = lint(pages)

report = WIKI.join("meta", "#{TODAY}-lint-report.md")
def write_lint_report(report, pages, findings)
  summary = [
    "---",
    "type: meta",
    "title: \"Wiki Lint Report — #{TODAY}\"",
    "status: mature",
    "created: \"#{TODAY}\"",
    "updated: \"#{TODAY}\"",
    "tags:",
    "  - meta",
    "  - lint-report",
    "---",
    "",
    "# Wiki Lint Report — #{TODAY}",
    "",
    "- Atomic pages scanned: #{pages.length}",
    "- Tracked source files checked: #{tracked_source_files.length}",
    "- Findings: #{findings.length}",
    ""
  ]
  if findings.empty?
    summary.concat(["## Result", "", "All metadata, coverage, orphan, dead-link, atomicity, callout, ADR-chain, and relative documentation-link checks passed.", ""])
  else
    findings.group_by(&:category).sort.each do |category, group|
      summary.concat(["## #{category}", ""])
      group.each { |finding| summary << "- `#{finding.path}` — #{finding.message}" }
      summary << ""
    end
  end
  report.write(summary.join("\n") + "\n")
  prettier = ROOT.join("frontend/node_modules/.bin/prettier")
  system(prettier.to_s, "--write", report.to_s, out: File::NULL) if prettier.executable?
end

write_lint_report(report, pages, findings)

if findings.empty?
  # Reconcile again with the lint report included, then validate the complete final corpus.
  pages = wiki_pages
  write_global_state(pages)
  findings = lint(pages)
  write_lint_report(report, pages, findings)
  write_global_state(pages) if findings.empty?
end

if findings.empty?
  puts "PASS: #{pages.length} atomic pages; #{tracked_source_files.length} tracked source files; 0 findings"
else
  warn "FAIL: #{findings.length} findings; see #{rel(report)}"
  exit 1
end
